Repository ultralytics/source-trace, pull requests merged in 2025-01, with the labels that each got.

#11 Ultralytics Refactor https://ultralytics.com/actions
  .github/workflows/format.yml
Labels: documentation, enhancement, devops

#12 Standardize license headers in Python files
  source/__init__.py
  source/run_repo.py
Labels: documentation

#14 Update README.md
  README.md
Labels: documentation, enhancement
